---
name: zprint-clj
description: Node.js wrapper for ZPrint Clojure source code formatter
homepage: https://github.com/clj-commons/zprint-clj
licenses:
  - MIT
languages:
  - Clojure
  - ClojureScript
categories:
  - Formatter

source:
  id: pkg:npm/zprint-clj@0.8.0

bin:
  zprint-clj: npm:zprint-clj
